AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  SaveWikiFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.saveWiki
      Runtime: nodejs18.x
      CodeUri: ./wiki
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatGPTTable
      Environment:
        Variables:
          CHAT_GPT_TABLE: !Ref ChatGPTTable
      Events:
        Api:
          Type: Api
          Properties: 
            Path: /wiki
            Method: POST
  
  GetWikiFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.getWiki
      Runtime: nodejs18.x
      CodeUri: ./wiki
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatGPTTable
      Environment:
        Variables:
          CHAT_GPT_TABLE: !Ref ChatGPTTable
      Events:
        ChatGPTAPI:
          Type: Api
          Properties:
            Path: /wiki
            Method: GET


  ChatGPTTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  MyApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/wiki/"
